name: Coverage

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  codecov-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.9
      - name: Install dependencies
        working-directory: simple-backend
        run: pip install -r requirements_dev.txt
      - name: Run tests and collect coverage
        working-directory: simple-backend
        run: pytest --cov-report xml --cov=simple_backend tests/
      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: simple-backend
          flags: backend
          file: coverage.xml
          verbose: true

  codecov-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Node.js 18
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.12.0
      - name: Install dependencies
        working-directory: simple-ui
        run: yarn
      - name: Run tests and collect coverage
        working-directory: simple-ui
        run: yarn coverage
      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: simple-ui/coverage/cypress/
          flags: frontend
          file: lcov.info
          verbose: true
