name: Deploy to DockerHub

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: ${{secrets.DOCKER_REPO}}
          registry: ${{secrets.DOCKER_REGISTRY}}
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          buildArgs: |
            SSH_KEY="${{secrets.DOCKER_RAIN_SSH_KEY}}"
          addLatest: true
